### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by StevenWingett** [StevenWingett/HiCUP#21]

**Comment by StevenWingett** [comment]
Add GitHub logo/link to documentation.

**Comment by navern0net** [comment]
> Add GitHub logo/link to documentation.

And also change a contact email! ;) The old one from Babraham doesn't work

**Comment by StevenWingett** [comment]
Updated in commit:
ce79a28ca9cd817d86677c04926bf7f0df5f016d
