### ISSUE TITLE
link for HiCUP v0.5.3

### ISSUE THREAD

**Issue by ivyhzau** [StevenWingett/HiCUP#52]
I want to repeat the results of a publication. But I failed to find the download link for HiCUP v0.5.3(the paper used). Where I can find the download link

**Comment by StevenWingett** [comment]
Hi,

HiCUP v0.5.3 can be dowloaded from: https://www.bioinformatics.babraham.ac.uk/projects/hicup/hicup_v0.5.3.tar.gz

You don't name the publication, so please note that HiCUP v0.5.8 was used for the HiCUP F1000 paper (https://zenodo.org/record/33388#.YNwu4xNKhhE)

I strongly recommend always using the latest version of HiCUP, which is available here on GitHub.

All the best,
Steven
