### ISSUE TITLE
Tutorial test data not pairing with HiCUP Mapper after bowtie2 alignment

### ISSUE THREAD

**Issue by aturocks** [StevenWingett/HiCUP#57]
[hicup_example_conf.txt](https://github.com/StevenWingett/HiCUP/files/6963710/hicup_example_conf.txt)

[HiCUP_error_std_output.txt](https://github.com/StevenWingett/HiCUP/files/6963704/HiCUP_error_std_output.txt)

I am trying to run the HiCUP 0.8.2 pipeline on the Yale University cluster, where I have installed all dependencies (R, SAMtools, bowtie2 etc) as modules.

There is a problem when I run the test data on HiCUP. After the pairing complete step, it showed that

"Can't read '/home/ap2549/project/capture_analysis_trial/HiCUP/output/test_dataset1.map.sam' : No such file or directory at /gpfs/ycga/project/noonan/ap2549/capture_analysis_trial/HiCUP/HiCUP-0.8.2/hicup_mapper line 552." 

Would you please help me to solve this? I am also attaching my conf file and the command line std output for your perusal.

Best,
Atreyo

**Comment by StevenWingett** [comment]
Hi Atreyo,

Thank you for your message and I'm sorry to learn you are experiencing problems with HiCUP.

In fact, other HiCUP users have reported similar issues.  It is often a result of Bowtie2 terminating unexpectedly and causing HiCUP to fail.  The usual cause of Bowtie2 failing is it running out of RAM.

Are you able to re-run the job, but maybe make sure you have 50GB (this should be much more than required) RAM allocated to your job?  

I hope that solves the issue, but please tell me how you get on.

All the best,
Steven

**Comment by aturocks** [comment]
Thanks a lot Steven - it seems that Bowtie2 failing was indeed the issue (it works for Bowtie properly). I'll check with the IT support here about what's going on with the version of Bowtie2 installed.

Best,
Atreyo

**Comment by StevenWingett** [comment]
Hi Atreyo,

I'm glad that was helpful.  I'll close the job for now, but please do let me know if you think HiCUP is actually the problem.  Were you able to allocate more memory to Bowtie2?  This may solve the problem.

Regards,

Steven
