### ISSUE TITLE
hicup_reporter can't run if it detects other previous reports

### ISSUE THREAD

**Issue by LaureTomas** [StevenWingett/HiCUP#58]
Hello!

I've just updated my version of HiCUP to the latest (0.8.2) and run it as usual for a new sample. In my directory structure, all the HiCUP output files are stored in the same folder for several samples and it wasn't a problem to generate the reports with the previous method (HTML); but now all is fine in the HiCUP pipeline except the hicup_reporter step because it detects that I have previous reports and won't continue with the new one.

Let me explain my case:
Several months ago I run the pipeline (0.7.2) for 2 samples, and all was fine. Now, I've updated the version (0.8.2) and run it with a new sample and when it reaches the hicup_reporter gives me the following error:
```
Creating combined HiCUP summary report
Reading folder '/my/output/path/
Writing to: /my/output/path/
	3 complete summary results groups identified in folder
Output file '/my/output/path/HiCUP_summary_report_nELHKeaSsU_11-11-57_17-01-2021.txt' already exists
Output file '/my/output/path/HiCUP_summary_report_JAqzREEjBU_05-48-27_18-06-2021.txt' already exists
Please adjust configuration.

```
It's ok that it doesn't repeat the previously done reports, but it would be great that it did the one that is missing, that is the one for the sample currently processing. Because otherwise, the pipeline couldn't finish and when running on a cluster the error means killing the job.

I hope there is an easy workaround to solve this.

Thanks.

**Comment by StevenWingett** [comment]
Hi,

Yes, the change from HiCUP v7 to v8 was a major update and I changed the reporting method.  

Could you simply move those HiCUP v7 text reports into another folder?   Then, run hicup_reporter.  When it is finished, move the text reports back to the original folder?

(Just as an aside, I do recommend processing all data for a single project all together, with the same versions of HiCUP and Bowtie2.  I know this is not possible while data is being generated in the lab, but once you have all the data, process everything together and use that as the starting point for your analysis.)

Does that solve your query? 

All the best,

Steven

**Comment by LaureTomas** [comment]
Thanks for the quick response.

I've already thought about moving all the reports from previous samples (both the complete report and the one for each step) to another folder and then move them back. But if a run several samples in parallel (i.e. in different jobs, not all in the same HiCUP config file) the problem will still be the same, since they will generate the reports in the same folder. When the first sample reaches the hicup_reporter step it will generate its reports, but when the second reaches that step will give the error since it detects the previous one.

Is there a way to provide a pattern to hicup_reporter, to only generate the report for the files with that given pattern? (Being the pattern, the random ID that HiCUP gives to the reports)

I completely agree with you with running all the data together with the same versions, I was just giving a try the new version with a sample. But even if I process all of them together with the same version, I will get the error. The only solution I can think of is running HiCUP in specific folders for each sample, otherwise, the reports will interfere.

Best

**Comment by StevenWingett** [comment]
Hi again,

Personally, I would run separate jobs in separate folders.  This prevents such confusion.  However, if you don't want to do this, what you can do is wait for all the HiCUP jobs to finish and then run HiCUP Reporter:

1) Run all HiCUP jobs (it may still fail at the reporting stage) 

2) Move the collated summary reports generated by hicup_reporter (e.g. HiCUP_summary_report_nELHKeaSsU_11-11-57_17-01-2021.txt) to another location (in case something goes wrong).

3) Run hicup_reporter:

hicup_reporter [folder name]

This should now process the intermediate summary files and generate your final collated reports.

Did that work?

Cheers.

**Comment by LaureTomas** [comment]
Yes, that works as a patch for now. But thinking on a permanent solution for my pipeline I think I should change my directory structure to run, as you say, separate jobs in separate folders.

Thank you so much.

Best.

**Comment by StevenWingett** [comment]
Excellent, I'm glad that helped.  I'll close this issue.

By the way, if you are going to follow the separate folder per job strategy for you pipeline, then I could mention that Nextflow pipeline DSL does that (https://www.nextflow.io/about-us.html).  It was developed initially by your neighbours at the CRG in Barcelona.

I have built a Nextflow HiCUP pipeline, if that is useful for you?

All the best,

Steven
