### ISSUE TITLE
HiCUP Deduplicator Headers

### ISSUE THREAD

**Issue by StevenWingett** [StevenWingett/HiCUP#6]
The HiCUP De-duplicator script is not writing out a full header, for example
@PG     ID:HiCUP Deduplicator VN:0.7.2
 
But instead, is only writing out:
@PG     VN:0.7.2

**Comment by jakevc** [comment]
If anyone else finds this issue, in the event that the bamfile containing this bug needs to be repaired without rerunning HiCUP, the following command will repair It:

```
samtools reheader -c "perl -ne 'if (/^@PG/) {s/HiCUP Dedup/ID:HiCUP Dedup/g}; print;'"  input.bam > output.bam 
```
