### ISSUE TITLE
di-tag parameter

### ISSUE THREAD

**Issue by ivyhzau** [StevenWingett/HiCUP#60]
I have tried different parameters of Maxima and Minima di-tag length. And about 20% loops are not shared with different parameters. If we doesn't know the selection fragment size, how to suitable parameters of longest and shortest di-tag length?

**Comment by StevenWingett** [comment]
Hi,

It is always a good idea to assess these values experimentally if you can, but if they are not available then the HiCUP defaults are suitable for most purposes.   (Indeed, flowcell preferences for certain lengths may cause the sequenced di-tag population length to be different from the population in the library, as determined by the bioanalyser).

After running HiCUP, I would check the report to ascertain whether the default lengths were appropriate (i.e. the curve did fit within these limits).  If not, you could try processing again with different limits.

Of course, the number of loops can vary owing to sequencing depth, library quality, di-tag filters.  What is important is that you process all the libraries with the same di-tag length cut-offs.  That way you can make fair comparisons between libraries/conditions.

I hope that helps.

Steven

**Comment by ivyhzau** [comment]
I have find that there is a di-tag length distribution in html report. I wonder whether we can determine the di-tag parameters by that distribution. And how to set the paramether? For the default parameter why set the range is 50-700? Recently, I have found that the suggested parameter in ChiCAGO pipeline for HiCUP is 150-800.

**Comment by ivyhzau** [comment]
@StevenWingett 
I have find that there is a di-tag length distribution in html report. I wonder whether we can determine the di-tag parameters by that distribution. And how to set the paramether? For the default parameter why set the range is 50-700? Recently, I have found that the suggested parameter in ChiCAGO pipeline for HiCUP is 150-800.

**Comment by StevenWingett** [comment]
Hi,

Yes, as I mentioned in my reply, you could refer to the the HTML report to set the di-tag lengths.  To set these lengths, simply **edit the configuration file** (or alternatively use the --longest and --shortest command line options).  For more details see: https://www.bioinformatics.babraham.ac.uk/projects/hicup/read_the_docs/html/index.html#running-hicup

The CHiCAGO reference may be referring to 4-cutter CHiC experiments.  If that is what you are doing, then follow those instructions.

You should typically select di-tag lengths similar to the HiCUP default setting.   In any case, always use the same parameters for all your samples in a single experiment.

I hope that helps.

All the best,

Steven
