### ISSUE TITLE
UMIs incorporated into deduplicator

### ISSUE THREAD

**Issue by aturocks** [StevenWingett/HiCUP#61]
Hi Steven,

I'm doing a cHiC experiment using adapters containing a 11bp UMI. I wanted to utilize identical UMIs as an additional criteria in the deduplication process to remove PCR duplicates (along with the usual criterion of removing reads mapping to the same start and end coordinates). Do you have any suggestions of how I can get HiCUP_dedup to do that? Or is there a package I can use in tandem with dedup to account for UMIs?

Best,
Atreyo

**Comment by StevenWingett** [comment]
Hi Atreyo,

I have used UMI tools (https://github.com/CGATOxford/UMI-tools) before to de-duplicate sequences based on both mapped position and UMI, but not with Hi-C related data.  

I suggest trying UMI-tools with the data produced by hicup_filter (i.e. before the de-duplication step).  Please be aware that HiCUP BAM files are ordered so that Hi-C di-tag read pairs are on adjacent lines.  This ordering must be maintained else the final output file with be meaningless.

That is my best suggestion.  You may need to parse the HiCUP BAM file into a format compatible with UMI-tools, which may require you to write some code.

I hope that helps.

All the best,

Steven

**Comment by aturocks** [comment]
Hi Steven,

Yes - I've tried using UMI tools after the HiCUP filter step, but it seems the deduplicated output from this is different from the HiCUP BAM file, and consequently cannot be used for downstream steps like CHiCAGO. Can the ordering be changed to the correct format using samtools? 

Best,
Atreyo

**Comment by aturocks** [comment]
Hi Felix,

Certainly, that'd be super helpful as I don't really have much experience modifying BAM file formats. In my case R1 and R2 are paired into ditags (but the UMI for ditags mapping to the same fragments should be consistent) Here are the files:

Dedup File when I use UMI tools (the file I want to use, but it's in the wrong format)
[dedup_filt.bam.gz](https://github.com/StevenWingett/HiCUP/files/7260380/dedup_filt.bam.gz)

Dedup File after regular HiCUP (correct format for downstream analyses)
[R1_2_umi.hicup.bam.gz](https://github.com/StevenWingett/HiCUP/files/7260382/R1_2_umi.hicup.bam.gz)

Thanks for offering to help me out! I will also take a look at your script.

Best,
Atreyo

**Comment by FelixKrueger** [comment]
Hi, would you mind also sending the file **before** deduplication so I can see if I can get it into the correct file format for downstream analsyses? I can start on it right now, but it would be good to have. Cheers

**Comment by FelixKrueger** [comment]
Actually I suppose I could use the R1_2 file as it has undergone deduplication but was not UMI-aware, isn't that right?

**Comment by aturocks** [comment]
Hi Felix, I have the file before filtering as well, but it's about 100MB, and can't be attached here. Maybe you can send me your email and I'll send it to you via there? And yes, the R1_2 file has undergone deduplication but was not UMI-aware.

**Comment by FelixKrueger** [comment]
100MB is a bit much for an email, but I can send you and FTP link if that helps? My email is in my profile.

**Comment by aturocks** [comment]
Sure thing - that works

**Comment by StevenWingett** [comment]
Hi,

Great that's working out.  I actually wasn't aware of UMI-Bam, as I'd have used it myself earlier this year.  Out of interest Felix, does it allow for mismatches in the UMI (which can be important for longer UMIs)?

If you need to sort the BAM file, try:

samtools sort -n [filename]

which will sort the file by FASTQ read name, which should restore the HiCUP pairing.

I hope that helps.

Steven

**Comment by FelixKrueger** [comment]
Yes, you can select `--mm` to allow mismatches (at least 1 or 2). In my tests, and for 8bp codes it didn't make much of a difference though - apart from increasing the compute time massively. It's not doing any clever neural network approaches of so, but rather doing exhaustive searches per position.

**Comment by FelixKrueger** [comment]
OK, I think I am getting somewhere. I just added a new option `--hic` to UmiBam, and here are the reports for the file you sent me:

**Read position only:**

`UmiBam --hic R1_2_umi.filt.bam`


```
Total number of alignments analysed in R1_2_umi.filt.bam:       553908
Total number duplicated alignments removed:     478869 (86.45%)

Total count of deduplicated leftover sequences: 75039 (13.55% of total)
```

**Read position + UMI (perfect matches):**

`UmiBam --hic --umi R1_2_umi.filt.bam`

```
Total number of alignments analysed in R1_2_umi.filt.bam:       553908
Total number duplicated alignments removed:     443688 (80.10%)

Total count of deduplicated leftover sequences: 110220 (19.90% of total)
```

I still need to figure out how to report the number of different positions for this as you can potentially have R1 + R2, or R2 + R1  combinations align to the same positions (or am I wrong there?). Could you maybe clone the current dev version of UmiBam, to see if it seems to do the right thing? I need to prepare dinner now, so to be continued....

**Comment by FelixKrueger** [comment]
I just had a quick look at this in SeqMonk, and I think it might be working as intended.

Here is a screenshot from some position on chromosome 22:

<img width="963" alt="Screenshot 2021-09-30 at 20 06 40" src="https://user-images.githubusercontent.com/5870509/135514956-9a350714-91f5-4c45-a847-8a994ffd3c1b.png">

Deduplication just by position results in just a single read pair:

```
SAM R1_2_umi.filt.deduplicated.bam | grep chr22 | grep 20987020
A00216R:670:HGTJHDSX2:3:1111:27380:22075:GGTCTTCGGTG	67	chr15	36886576	0	122M4I16M3I6M	chr22	20987020	0	AAGCATTAAAATTCGCTTTAATTGAGAAAATATTGATTTTTAAGTCTAGAAAAAGCGAAATCGTAATTTAGCTTCAAACTTTCAGGCGAGAATATAGCGTATTATGTCGCCGTATAATGGATCCGCCCACCTCAGCCTCCCAAAGTGCTGG	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	AS:i:-71	XN:i:0	XM:i:8	XO:i:2	XG:i:7	NM:i:15	MD:Z:127C0T0T0T2G7A0A0C0	YT:Z:UU	CT:Z:TRANS
A00216R:670:HGTJHDSX2:3:1111:27380:22075:GGTCTTCGGTG	131	chr22	20987020	42	29M1D122M	chr15	36886576	0	TGCCTATTTTGTTTTTTCCTTATTGGTGATTTTTTTTTTTAAGTTTCTATGATGAGACAGGTATCACCTTCAAAATACAAAAGTGAAACGTAGCTGGGCGCGGTGGCTCACGCCTGTAATCCCAGCACTTTGGGAGGCTGAGGTGGGCGGA	FFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	AS:i:-8	XN:i:0	XM:i:0	XO:i:1	XG:i:1	NM:i:1	MD:Z:29^T122	YT:Z:UU	CT:Z:TRANS
```

Deduplicating by position as well as UMI finds the following 4 reads:

```SAM R1_2_umi.filt.UMI_deduplicated.bam | grep chr22 | grep 20987020
A00216R:670:HGTJHDSX2:3:1111:27380:22075:GGTCTTCGGTG	67	chr15	36886576	0	122M4I16M3I6M	chr22	20987020	0	AAGCATTAAAATTCGCTTTAATTGAGAAAATATTGATTTTTAAGTCTAGAAAAAGCGAAATCGTAATTTAGCTTCAAACTTTCAGGCGAGAATATAGCGTATTATGTCGCCGTATAATGGATCCGCCCACCTCAGCCTCCCAAAGTGCTGG	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	AS:i:-71	XN:i:0	XM:i:8	XO:i:2	XG:i:7	NM:i:15	MD:Z:127C0T0T0T2G7A0A0C0	YT:Z:UU	CT:Z:TRANS
A00216R:670:HGTJHDSX2:3:1111:27380:22075:GGTCTTCGGTG	131	chr22	20987020	42	29M1D122M	chr15	36886576	0	TGCCTATTTTGTTTTTTCCTTATTGGTGATTTTTTTTTTTAAGTTTCTATGATGAGACAGGTATCACCTTCAAAATACAAAAGTGAAACGTAGCTGGGCGCGGTGGCTCACGCCTGTAATCCCAGCACTTTGGGAGGCTGAGGTGGGCGGA	FFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	AS:i:-8	XN:i:0	XM:i:0	XO:i:1	XG:i:1	NM:i:1	MD:Z:29^T122	YT:Z:UU	CT:Z:TRANS

A00216R:670:HGTJHDSX2:3:1142:21875:28166:CGATAGCCAGT	67	chr22	20987020	42	151M	chr15	36886576	0	TGCCTATTTTGTTTTTTCCTTATTGGTGATTTTTTTTTTTTAAGTTTCTATGATGAGACAGGTATCACCTTCAAAATACAAAAGTGAAACGTAGCTGGGCGCGGTGGCTCACGCCTGTAATCCCAGCACTTTGGGAGGCTGAGGTGGGCGG	FFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFF:FFFFFFFFFF:FFFFFFFFF	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:151	YT:Z:UU	CT:Z:TRANS
A00216R:670:HGTJHDSX2:3:1142:21875:28166:CGATAGCCAGT	131	chr15	36886576	0	122M4I16M3I6M	chr22	20987020	0	AAGCATTAAAATTCGCTTTAATTGAGAAAATATTGATTTTTAAGTCTAGAAAAAGCGAAATCGTAATTTAGCTTCAAACTTTCAGGCGAGAATATAGCGTATTATGTCGCCGTATAATGGATCCGCCCACCTCAGCCTCCCAAAGTGCTGG	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF,FFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFF	AS:i:-71	XN:i:0	XM:i:8	XO:i:2	XG:i:7	NM:i:15	MD:Z:127C0T0T0T2G7A0A0C0	YT:Z:UU	CT:Z:TRANS

A00216R:670:HGTJHDSX2:3:2251:27624:23281:CGATAGCCCGT	67	chr22	20987020	3	151M	chr15	36886576	0	TGCCGATTTTGTTTTTTCCTTATTGGTGATTTTTTTTTTTTAAGTTTCTAAGATTAGACAGGTATCACATTCAAAATACAAAAGTTAAACGTAGCTGGGCGCGGTGGATCCCGACTGAAATCCCAGCACATTGCTAGCGGTAGGTTGGAGG	F:FF,FFF:FFF,FFFF:F,F,F,FFFFFF,F,F,:,FF:F::,:FF,,:,,,,,,,F,FF,FFF:FF:,::FFFF::,,:F,:F,FFFFF:FF,F:,,,,:FF:,,,F,::F,F::,:F:F,,:,::,,FFF,,,F,,:,:FFF,FF,,F	AS:i:-57	XN:i:0	XM:i:18	XO:i:0	XG:i:0	NM:i:18	MD:Z:4T45T3G13C16G21C2A2C3T11T3G0G2G0C0T0G4G2C2	YT:Z:UU	CT:Z:TRANS
A00216R:670:HGTJHDSX2:3:2251:27624:23281:CGATAGCCCGT	131	chr15	36886576	0	130M4I8M3I6M	chr22	20987020	0	AAGCATTAAAATTCGCTTTAATTGAGAAAATATTGATTTTTAAGTCTAGAAAAAGCGAAATCGTAATTTAGCTTCTAACTTTCAGGCGAGAATATAGCGTATTATGTCGCCGTATAATGGATCCGCCCACCTCACCCTCCCAAAGTGCTGG	FF::FFFFFFF:F,::FFFFFFFFFFFFFFF:FFFFFF,FFFFF:FF:FF:FF,FFFF:::FF:FFF:FF,FFFF,:::,:,FFF:,,FFF,FFFFFF,F,F,FFF,F,:,FF,::FFFF:FFFFF,F:,F:FF,,FFFFFFF,:F:F,:F	AS:i:-66	XN:i:0	XM:i:9	XO:i:2	XG:i:7	NM:i:16	MD:Z:75A48A3T0T0T2G7A0A0C0	YT:Z:UU	CT:Z:TRANS

A00216R:670:HGTJHDSX2:3:2317:7012:35931:CGATAGCCGGT	67	chr22	20987020	42	151M	chr15	36886576	0	TGCCTATTTTGTTTTTTCCTTATTGGTGATTTTTTTTTTTTAAGTTTCTATGATGAGACAGGTATCACCTTCAAAATACAAAAGTGAAACGTAGCTGGGCGCGGTGGCTCACGCCTGTAATCCCAGCACTTTGGGAGGCTGAGGTGGGCGG	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFF:FFFFFFFFFFFFFFFF:FFFFFFF:F:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFF:FFFFFFFFFFFFFFFFFFFFF	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:151	YT:Z:UU	CT:Z:TRANS
A00216R:670:HGTJHDSX2:3:2317:7012:35931:CGATAGCCGGT	131	chr15	36886576	0	128M1I3M3I7M3I6M	chr22	20987020	0	AAGCATTAAAATTCGCTTTAATTGAGAAAATATTGATTTTTAAGTCTAGAAAAAGCGAAATCGTAATTTAGCTTCAAACTTTCAGGCGAGAATATAGCGTATTATGTCGCCGTATAATGGATCCGCCCACCTCAGCCTCCCAAAGTGCTGG	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF:FFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFF:FFFFF:FFFF:,FFFFF:FFFFF:FFFFFFFF	AS:i:-67	XN:i:0	XM:i:7	XO:i:3	XG:i:7	NM:i:14	MD:Z:124A3T0T3G7A0A0C0	YT:Z:UU	CT:Z:TRANS
```

Whether these reads now actually carry truly different UMIs, or might just be single-base errors in the same UMI is another question, but in theory it seems to be doing what I set out to do!

**Comment by StevenWingett** [comment]
Thanks Felix, that is a useful development.

That is an important point you make: i.e. whether different UMIs actually constitute the same UMI.  UMI-tools tried to assess this using a network-based method: https://cgatoxford.wordpress.com/2015/08/14/unique-molecular-identifiers-the-problem-the-solution-and-the-proof/

Hopefully these options will solve the interesting UMI/CHiC analysis.

All the best,

Steven

**Comment by FelixKrueger** [comment]
The number of positions affected should now also be correct. 

**Hi-C mode (positional only):**
```
::::::::::::::
R1_2_umi.filt.deduplication_report.txt
::::::::::::::

Total number of alignments analysed in R1_2_umi.filt.bam:	553908
Total number duplicated alignments removed:	478869 (86.45%)
Duplicated Hi-C alignments were found at: 	55058 different positional combinations

Total count of deduplicated leftover sequences: 75039 (13.55% of total)
```

**Hi-C mode (positional + UMI (unique)):**
```
::::::::::::::
R1_2_umi.filt.UMI_deduplication_report.txt
::::::::::::::

Total number of alignments analysed in R1_2_umi.filt.bam:	553908
Total number of sequences were unaligned:	0
Total number duplicated alignments removed:	443688 (80.10%)
Duplicated Hi-C alignments were found at: 	53316 different positional combinations

Total count of deduplicated leftover sequences: 110220 (19.90% of total)
```

For the sake of completeness I will now also look at enabling the `--hic` method to work with an edit distance (different number of mismatches). My guess would be that considering an edit distance of 1 as duplicates, or in other words allowing 1 mismatch in the UMI, would deal with the vast majority of all situations. But I am sure that a network-based directional adjacency method has its merits and is superior methodology-wise (that being said, there is a chance that it won't make a difference for a bog-standard Hi-C experiment).

I'll report here one last time once I've got the edit distance/`--mm` mode working. The options for perfect matches `--hic --umi` should be considered functional as is.

**Comment by aturocks** [comment]
Hi Felix,

Thanks a lot! I just ran the UmiBam file with the --hic and --umi tags and it seems to give the same results as you wrote above. I think it would be great if we could add the -mm tag to give a threshold for max number of mismatches tolerated. Otherwise, I will rerun CHiCAGO on this deduplicated version to see if things look good and let you know. 

One question/modification I wanted to add: is it possible to include in the summary report the UMIs and the number of reads corresponding to each UMI. That'd be helpful to plot out the number of ligation events at certain locations in the genome containing targets I enriched for in the cHiC experiment.

Thanks again for your help!

Best,
Atreyo

**Comment by FelixKrueger** [comment]
I think I got the mismatch option to work as well

**Hi-C mode (positional + UMI (`--mm 1`)):**
```
::::::::::::::
R1_2_umi.filt.UMI_1mm_deduplication_report.txt
::::::::::::::
UMIs closer than, or equal to, an edit distance of >>1<< were considered duplicates:
====================================================================================
Total number of alignments analysed in R1_2_umi.filt.bam:	553908
Total number duplicated alignments removed:	449982 (81.24%)
Total count of deduplicated leftover sequences: 103926 (18.76% of total)
```

**Hi-C mode (positional + UMI (`--mm 2`)):**
```
::::::::::::::
R1_2_umi.filt.UMI_2mm_deduplication_report.txt
::::::::::::::
UMIs closer than, or equal to, an edit distance of >>2<< were considered duplicates:
====================================================================================
Total number of alignments analysed in R1_2_umi.filt.bam:	553908
Total number duplicated alignments removed:	451015 (81.42%)
Total count of deduplicated leftover sequences: 102893 (18.58% of total)
```

Regarding your request about the UMIs and counts, is really all you would like to have a list like this:

```
GTGATATAGTT 12
CGAACAATACC 2
GGGCGGGCTGT 1
ATCGTGGACCG 3
...
```

? Or per position? Or UMIs plus all read (IDs) supporting it? Feel free to experiment with the latest version of UmiBam with `--mm`

**Comment by aturocks** [comment]
Hi Felix,

Great, thanks! For the summary, I was thinking more of the UMI, read count corresponding to the UMI, R1 coordinates, R2 coordinates in a tab-delimited table. I think a list of UMI, read IDs and counts will also work fine

Best,
Atreyo

**Comment by FelixKrueger** [comment]
Hi Atreyo,

Something like this?

```
Now printing detailed UMI report

GCACTTACGAT	1	chr4	30738859	chr4	26255459
TTTAGCAAAGA	1	chr8	38079787	chr8	38380483
TAATACCGGTA	1	chr17	66395251	chr17	65529850
GGTTAATTCCC	3	chr17	2238466	chr17	2245442
GGTTAATTCCC	3	chr17	2238466	chr17	2245442
GGTTAATTCCC	3	chr17	2238466	chr17	2245442
TAGTCCGGATT	1	chr7	25861456	chr1	145991792
ATCCGTTACGT	3	chr14	33396691	chr14	33789924
ATCCGTTACGT	3	chr14	33396691	chr14	33789924
ATCCGTTACGT	3	chr14	33396691	chr14	33789924
GGAACTTATTG	2	chr14	33777486	chr14	34191471
GGAACTTATTG	2	chr14	33777485	chr14	34191471
CATTTTAGTCC	1	chr20	728941	chr20	2258816
TGTCTATCGTT	10	chr17	2238567	chr17	2224128
TGTCTATCGTT	10	chr17	2238567	chr17	2224128
TGTCTATCGTT	10	chr17	2238567	chr17	2224128
TGTCTATCGTT	10	chr17	2238567	chr17	2224128
TGTCTATCGTT	10	chr17	2238567	chr17	2224128
TGTCTATCGTT	10	chr17	2238567	chr17	2224128
TGTCTATCGTT	10	chr17	2238567	chr17	2224128
TGTCTATCGTT	10	chr17	2238567	chr17	2224128
TGTCTATCGTT	10	chr17	2238567	chr17	2224128
TGTCTATCGTT	10	chr17	2238567	chr17	2224128
```

Maybe sorted in a descending fashion? Please note that I have opened an issue for UmiBam directly so that we don't spam Steven's repo too much.... (https://github.com/FelixKrueger/Umi-Grinder/issues/2)

**Comment by aturocks** [comment]
Hi Felix,

Yes,

That looks perfect. Does UmiBam generate this report automatically whenever I dedpulicate a bam? This was basically what I wanted, thanks for all your help.

Best,
Atreyo

**Comment by FelixKrueger** [comment]
I will add a new option for this, called `--detailed` or something. In the current implementation it works in `--mm` mode, but I guess you want to be universal even for perfect matches?

**Comment by aturocks** [comment]
Yes, a general flag would be great

**Comment by FelixKrueger** [comment]
OK, I have now added a new option `--detail`, that should generate the desired detailed report. It currently only works in `--mm` mode, but I will try too add it for perfect match (no mismatches) mode later as well.

A working command should be:
```
UmiBam --hic R1_2_umi.filt.bam --umi --mm 1 --detail
```
Can you give it a go to see if this is what you had in mind?

**Comment by FelixKrueger** [comment]
I think it now works in all sorts of `--hic` settings, with or w/o `--umi`, with or w/o `--mm`. Let me know if it works in your hands, if yes I can make a new release. Cheers and have a good weekend.

**Comment by aturocks** [comment]
Hi Felix,

That's great. Did you upload the new version? Because when I run the command I get an empty detailed report file with the following header:

MI	count	R1 chrom	R1 pos	R2 chrom	R2 pos

Otherwise the deduplication is working great.

Best,
Atreyo

**Comment by FelixKrueger** [comment]
Hmm, there is a chance I didn't... Can you check now? Apologies...
