### ISSUE TITLE
Truncation of 3' Partial Ligation Sequences

### ISSUE THREAD

**Issue by StephenRicher** [StevenWingett/HiCUP#63]
Hi,

During the HICUP Truncation step, partial ligation sequences may occur at the 3' end of reads and would escape truncation.  In such cases would it be better to truncate partial sequences if they occur at the 3' end.

Thanks,
Stephen

**Comment by StevenWingett** [comment]
Hi again,

I'm not sure I completely follow.  Would you mind giving an example?

Many thanks,

Steven

**Comment by StephenRicher** [comment]
Hi Steven,

Things are going well in Bath thanks, not long until I finish, it's amazing how fast time has flown! Hope things are well with you.

My thinking was if we are using say Mbo1 (^GATC) with ligation sequence GATCGATC and observe the following sequence:

ATCTAGCTAGCTACATCGATTT**GATCGA**

Since we observe a partial ligation sequence (GATCGA) might it good to assume this would have been an exact match to the ligation site had the read been longer and truncate the GA bases to:

ATCTAGCTAGCTACATCGATTT**GATC**

So in the case of Mbo1 I guess we would want to search additionally for the patterns: "GATCGAT$", "GATCGA$" and "GATCG$". I'm not sure how much this would improve mapping though - at most we'd remove a few bases on a relatively small proportion of reads. Just had the thought when writing up some methods so thought I'd see if it made sense.

Have a good weekend,
Stephen

**Comment by StevenWingett** [comment]
Hi Stephen,

Oh wow, yes time does fly.  I'm glad HiCUP was useful in your research. Are you planning to carry on in research?

Ah, I see what you mean now and yes this had occurred to us not long after publishing the code.  I seem to remember we decided against adding extra code for this corner case as it would have very likely a small effect on the results.  But this is a good point.  You could try trimming some FASTQ files and see how it affects the results.

Thanks for your comments.

All the best,
Steven

**Comment by StephenRicher** [comment]
Thanks yeah it would be interesting to see what proportion it impacts but presumably a minuscule fraction for a quite high computational cost of all the extra pattern checks.

At the moment I am keeping my options open, I've got short contract in a data science role straight after my PhD which will give me some time to think about it and [possibly look out for some post-docs.
