### ISSUE TITLE
how to chose --format option while running hicup_mapper

### ISSUE THREAD

**Issue by Giuseppe1995** [StevenWingett/HiCUP#65]
Hi, 
First of all, thanks and congrats for your tool, it's very user-friendly and efficient.
I had a doubt when running hicup_mapper. more in detail I am not sure about what --format option to use. For example, if my data have been sequenced via an Illumina HiSeq 2500 instrument, have I to chose `Sanger`, `Solexa_Illumina_1.0`, `Illumina_1.3` or `Illumina_1.5`? Is there a way to find out what option to use? 
Thank you in advance,
Giuseppe

**Comment by StevenWingett** [comment]
Hi Giuseppe,

Thanks for your kind message.

Virtually all recent (about 2015 and later) sequencing runs will be in Sanger format.  If I remember correctly, if you do not specify a format then HiCUP will try to calculate it for you.

Also the software tool FastQC (https://www.bioinformatics.babraham.ac.uk/projects/fastqc/ ) will tell you the format of a FASTQ file. (I think the information is reported in the Basic Statistics section of the FastQC report.)

I hope that helps.

All the best,
Steven
