### ISSUE TITLE
HiCUP error after pairing - Error in read.table/no lines available in input/Could not produced hicup_mapper summary/fail to read the header from "pair.bam"

### ISSUE THREAD

**Issue by matteozoia4** [StevenWingett/HiCUP#67]
Dear all,

I have samtools and bowtie2 up-dated and installed the R packages required (tidyverse / plotly) as well.
I don't know from where the header error could came from I have never encountered such an issue since the .conf file used it is has a very standardised form and files have been read correctly from Hicup Truncater:

`Starting HiCUP pipeline (v0.8.3)
PLEASE NOTE: FROM VERSION 8, HICUP REQUIRES THE R PACKAGES TIDYVERSE AND PLOTLY INSTALLED
SEE DOCUMENTATION FOR MORE DETAILS
Detecting R automatically
Found R at '/data/users/mzoia/anaconda3/envs/htseq_pipelines/bin/R'
Reading genome digest file '/data/projects/p616_Cis-regulatory_landscapes_in_heart_development/htseq_pipelines/HI-C/mm10_Hand2_Hi-C_GuillaumePIP/mm10_Hand2_HiC/Digest_mm10_DpnII_None_13-21-44_15-03-2022.txt' to determine Hi-C restriction enzyme
Truncating with HiCUP Truncater v0.8.3
Truncating sequences at occurrence of sequences '[GATC]'
Truncating sequences
Truncating s_2_1_Hand2FL.fastq.gz
Truncating s_2_2_Hand2FL.fastq.gz
Truncating s_1_1_Hand2MD.fastq.gz
Truncating s_1_2_Hand2MD.fastq.gz
Truncating s_3_2_Hand2HT.fastq.gz
Truncating s_3_1_Hand2HT.fastq.gz
Truncating complete
Mapping with HiCUP Mapper v0.8.3
Using aligner 'bowtie2'
Mapping complete
Pairing files with HiCUP Mapper v0.8.3
Pairing s_1_1_Hand2MD.map.sam and s_1_2_Hand2MD.map.sam
Pairing s_2_1_Hand2FL.map.sam and s_2_2_Hand2FL.map.sam
Pairing s_3_1_Hand2HT.map.sam and s_3_2_Hand2HT.map.sam
s_2_1_Hand2FL.trunc.fastq.gz does not exits in summary results hash.
s_1_1_Hand2MD.trunc.fastq.gz does not exits in summary results hash.
s_3_1_Hand2HT.trunc.fastq.gz does not exits in summary results hash.
Pairing complete
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
Calls: read.delim -> read.table
Execution halted
Could not produce hicup_mapper summary bar chart: /data/users/mzoia/anaconda3/envs/htseq_pipelines/bin/Rscript /data/projects/p616_Cis-regulatory_landscapes_in_heart_development/htseq_pipelines/HI-C/Softwares_HI-C_Guillaume_pipeline/HICUP_v0.8.3/r_scripts/hicup_mapper_summary.r ./ ./hicup_mapper_summary_shHjZdRlkJ_10-02-14_25-04-2022.txt: Operation not permitted at /data/projects/p616_Cis-regulatory_landscapes_in_heart_development/htseq_pipelines/HI-C/Softwares_HI-C_Guillaume_pipeline/HICUP_v0.8.3/hicup_mapper line 240.
[main_samview] fail to read the header from "s_3_1_2_Hand2HT.pair.bam".
s_3_1_2_Hand2HT.pair.bam contains no data
[main_samview] fail to read the header from "s_2_1_2_Hand2FL.pair.bam".
s_2_1_2_Hand2FL.pair.bam contains no data
[main_samview] fail to read the header from "s_1_1_2_Hand2MD.pair.bam".
s_1_1_2_Hand2MD.pair.bam contains no data
All the files in the HiCUP pipeline have been removed for containing no data.
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=7886599.0 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: binfservas11: task 0: Out Of Memory`

Best regards and thank you for your help,

MZ

**Comment by StevenWingett** [comment]
Hi,

I suspect you have run out of RAM during the mapping:

slurmstepd: error: Detected 1 oom-kill event(s) in StepId=7886599.0 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler. srun: error: binfservas11: task 0: Out Of Memory

Could you allocate more memory using Slurm?

All the best,
Steven

**Comment by matteozoia4** [comment]
Hi Steven,


many thanks for your prompt answer!

Yes sure I can, how much do you advice to set as memory to run three process on 12 threads?


Best regards,


MZ


Zoia Matteo, Ph.D. Student
Gene Regulation & Cardiac Development

Marco Osterwalder Laboratory
Department for BioMedical Research (DBMR)
University of Bern
Lab 369, Murtenstrasse 28
CH - 3008 Bern
SWITZERLAND

________________________________
Da: Steven Wingett ***@***.***>
Inviato: lunedì, 25. aprile 2022 11:57:40
A: StevenWingett/HiCUP
Cc: Zoia, Matteo (DBMR); Author
Oggetto: Re: [StevenWingett/HiCUP] HiCUP error after pairing - Error in read.table/no lines available in input/Could not produced hicup_mapper summary/fail to read the header from "pair.bam" (Issue #67)


Hi,

I suspect you have run out of RAM during the mapping:

slurmstepd: error: Detected 1 oom-kill event(s) in StepId=7886599.0 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler. srun: error: binfservas11: task 0: Out Of Memory

Could you allocate more memory using Slurm?

All the best,
Steven

**Comment by StevenWingett** [comment]
Hi,

This might be much more memory than you need.  Try 6 threads - 60GB.

Does that work (you can specify less memory next time and Slurm should give you an idea of the RAM actually used).

All the best,
Steven

**Comment by matteozoia4** [comment]
Many thanks!

I will try and get back to you - if the memory was indeed the problem we can close the opened issue.

Many thanks again!

Best,

MZ

**Comment by matteozoia4** [comment]
It worked many thanks!

Best,

MZ

**Comment by StevenWingett** [comment]
Excellent, increasing RAM usually solves issues of this kind.
