### ISSUE TITLE
Summary report file

### ISSUE THREAD

**Issue by Oksanak22** [StevenWingett/HiCUP#68]
Hi. I tried to run a pipeline followed by this video. But at the end, I don't have a summary report file. Who can help me to find the solution? Thank you.

**Comment by StevenWingett** [comment]
Thank you for your message.  

Could you please provide me with the command you ran and the output written to the screen by HiCUP.  What files were generated by HiCUP?

Thanks,

Steven

**Comment by Oksanak22** [comment]
Hello.

Thank you for your response.

I have run hicup --config hicup_example.conf  and I got bunch of files: 

hicup_mapper_summary…txt

hicup_truncater_summary…txt

test_dataset1.fastq.truncation_barchart.svg

test_dataset1.trunc.fastq.gz.mapper_barchart.svg

test_dataset1_2.pair.bam

test_dataset1_2.pair.bam.bak

test_dataset2.fastq.truncation_barchart.svg

test_dataset2.trunc.fastq.gz.mapper_barchart.svg

 

But I don’t see any summary file with .html extension as it shown on the video.

 

Thank you

**Comment by StevenWingett** [comment]
Hi,

There should be a *.hicup.bam file as well.

Usually HiCUP fails if not enough memory has been reserved for the mapping.  Are you able to re-run HiCUP but reserving 20GB RAM?  Does that work?

If not, would you be able to send me:
1) your HiCUP configuration file
2) the command you entered to run HiCUP
3) the standard out (text written to the screen) when HiCUP runs

Thanks,
Steven

**Comment by Oksanak22** [comment]
Hello,
Now when I tried to run hicup --config hicup_example.conf it gave me an error that ""PLEASE NOTE: FROM VERSION 8, HICUP REQUIRES THE R PACKAGES TIDYVERSE AND PLOTLY INSTALLED".

**Comment by StevenWingett** [comment]
Hi,

That is not an error message, it is just a reminder to make sure you have those R packages installed.  Do you have them installed?

Are you able to send me the full message written to the screen when HiCUP is run?

Regards,
Steven

**Comment by Oksanak22** [comment]
Thanks, finally I was able to run HiCUP.

**Comment by StevenWingett** [comment]
Great news.  Do you know why it was not working before?

Thanks,
Steven
