### ISSUE TITLE
what is the difference between hicup.bam and pair.bam? Why not all files will produce hicup.bam?

### ISSUE THREAD

**Issue by xsq2022** [StevenWingett/HiCUP#69]
what is the difference between hicup.bam and pair.bam? Why not all files will produce hicup.bam?

**Comment by StevenWingett** [comment]
Hi,

The pair.bam file contains the di-tag information after mapping and pairing.  The hicup.bam files contain the di-tag information after mapping, pairing, filtering and de-duplicating (i.e. once HiCUP has finished running).

You should have generated a *.hicup.bam (or sam) file once HiCUP has finished running successfully.  To retain intermediate SAM/BAM files, add the --keep option to your initial command.

(If you have a *.pair.bam file but no *.hicup.bam file, then HiCUP has not completed successfully.  Re-running HiCUP with more reserved RAM may resolve this).

Regards, 
Steven

**Comment by xsq2022** [comment]
Very happy to receive your reply. Thank you very much.---- Replied Message ----FromSteven ***@***.***>Date09/14/2022 23:31 ***@***.***> ***@***.******@***.***>SubjectRe: [StevenWingett/HiCUP] what is the difference between hicup.bam and pair.bam? Why not all files will produce hicup.bam? (Issue #69)
Closed #69 as completed.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/StevenWingett/HiCUP/issues/69#event-7387072998",
"url": "https://github.com/StevenWingett/HiCUP/issues/69#event-7387072998",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
