### ISSUE TITLE
Multi-thread option for Hicup filter and deduplicator.

### ISSUE THREAD

**Issue by Shubhamverma-bioinfo** [StevenWingett/HiCUP#71]
Hi @StevenWingett @rdali 
I'm running HiCUP pipeline on deep sequences paired end fastq data, Hicup provides the threads option to run the pipeline on multiple cores but based on CPU usage log, I can see Hicup filter and deduplicator steps are not using all cores provided.
I'm having config file were all parameter are specified to run HICUP pipeline, Can you guys please let me how I can enable threads option for hicup filter and deduplicator steps.

**Comment by StevenWingett** [comment]
Hi,

Thanks for your message.  Presumably you have specified the desired --threads option on the command line (or in the config file)?

I've not looked at the codebase for some time, but I suspect those steps may process each file with a maximum of 1 core per file.  Is that what you are seeing? 

Regards,
Steven
