### ISSUE TITLE
How to use the outputfile hicup.bam to run 3ddna 

### ISSUE THREAD

**Issue by Biscuite-wzy** [StevenWingett/HiCUP#73]
hi,
Thank you for developing useful tools. Now I have run the whole pipeline and obtained all results. I want to use the  output to run 3D-DNA to assemble. Which file I should use and how to address it. I hope you can help me. Thanks.

**Comment by StevenWingett** [comment]
Thank you for your message.  What do you mean by "3D-DNA" ?

**Comment by Biscuite-wzy** [comment]
Yes. I mean by "3D-DNA"




787117923
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StevenWingett/HiCUP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月23日(星期五) 凌晨1:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StevenWingett/HiCUP] How to use the outputfile hicup.bam to run 3ddna  (Issue #73)





 
Thank you for your message.  What do you mean by "3D-DNA" ?

**Comment by StevenWingett** [comment]
Hi,

I do not understand.  What is:

787117923
***@***.***

What are you trying to do?

Thanks,
Steven

**Comment by StevenWingett** [comment]
I'll close this issue for now, until further clarification.
