### ISSUE TITLE
index error

### ISSUE THREAD

**Issue by TakatoG** [StevenWingett/HiCUP#75]
Hi,
I made configuration file, and run HiCUP.
Then the error massage is always as follows.
 HiCUP-0.8.3/hicup --config HiCUP-0.8.3/config_files/hicup_example.conf
Starting HiCUP pipeline (v0.8.3)
PLEASE NOTE: FROM VERSION 8, HICUP REQUIRES THE R PACKAGES TIDYVERSE AND PLOTLY INSTALLED
SEE DOCUMENTATION FOR MORE DETAILS
bowtie2 index file '/Users/takato/mm10.1.bt2' does not exist
bowtie2 index file '/Users/takato/mm10.2.bt2' does not exist
bowtie2 index file '/Users/takato/mm10.3.bt2' does not exist
bowtie2 index file '/Users/takato/mm10.4.bt2' does not exist
bowtie2 index file '/Users/takato/mm10.rev.1.bt2' does not exist
bowtie2 index file '/Users/takato/mm10.rev.2.bt2' does not exist
Detecting R automatically
Found R at '/opt/homebrew/bin/R'
Please change configuration file and/or command-line parameters and/or installation accordingly

Do you know how to solve problem?

**Comment by StevenWingett** [comment]
Hi,

HiCUP is warning you that a Bowtie2 index file does not exist.

What happens if you type in the command line:

```
ls /Users/takato/mm10.rev.1.bt2
```

Does it find the file?

**Comment by TakatoG** [comment]
Hi, thank you for your reply!
Actually it was my mistake. I solved yesterday!
