### ISSUE TITLE
R error?

### ISSUE THREAD

**Issue by TakatoG** [StevenWingett/HiCUP#76]
Hi, 
I do not know the mean of follows message ...
Do you know what happened?

base) [t-goto@gwB1 ~]$ HiCUP-0.8.3/hicup --config HiCUP-0.8.3/config_files/hicup_example.conf
Starting HiCUP pipeline (v0.8.3)
PLEASE NOTE: FROM VERSION 8, HICUP REQUIRES THE R PACKAGES TIDYVERSE AND PLOTLY INSTALLED
SEE DOCUMENTATION FOR MORE DETAILS
Detecting R automatically
Found R at '/home/t-goto/local/bin/R'
Reading genome digest file 'Digest_mm10_re1_unspecified_None_11-50-59_24-01-2023.txt.gz' to determine Hi-C restriction enzyme
R not found at '/home/t-goto/local/bin/R'
Detecting R automatically
Found R at '/home/t-goto/local/bin/R'
Truncating with HiCUP Truncater v0.8.3
Truncating sequences at occurrence of sequences '[AAGCTAGCTT]'
Truncating sequences
Truncating Nature_neuro/SRR12066917_1.fastq.gz
Truncating Nature_neuro/SRR12066917_2.fastq.gz

/home/t-goto/local/lib64/R/bin/exec/R: error while loading shared libraries: libblas.so.3: cannot open shared object file: No such file or directory
Could not produce hicup_truncater summary bar chart: /home/t-goto/local/bin/Rscript /lustre7/home/t-goto/HiCUP-0.8.3/r_scripts/hicup_truncater_summary.r Nature_neuro/results/ Nature_neuro/results/hicup_truncater_summary_MvZOrHJiIH_19-45-44_01-02-2023.txt:  at /lustre7/home/t-goto/HiCUP-0.8.3/hicup_truncater line 281.
Truncating complete
R not found at '/home/t-goto/local/bin/R'
Detecting R automatically
Found R at '/home/t-goto/local/bin/R'
Mapping with HiCUP Mapper v0.8.3
Using aligner 'bowtie2'
Mapping Nature_neuro/results/SRR12066917_2.trunc.fastq.gz
Mapping Nature_neuro/results/SRR12066917_1.trunc.fastq.gz

Mapping complete
Pairing files with HiCUP Mapper v0.8.3
Pairing SRR12066917_1.map.sam and SRR12066917_2.map.sam
Nature_neuro/results/SRR12066917_1.trunc.fastq.gz does not exits in summary results hash.
Pairing complete
/home/t-goto/local/lib64/R/bin/exec/R: error while loading shared libraries: libblas.so.3: cannot open shared object file: No such file or directory
Could not produce hicup_mapper summary bar chart: /home/t-goto/local/bin/Rscript /lustre7/home/t-goto/HiCUP-0.8.3/r_scripts/hicup_mapper_summary.r Nature_neuro/results/ Nature_neuro/results/hicup_mapper_summary_MvZOrHJiIH_19-45-44_01-02-2023.txt: Inappropriate ioctl for device at /lustre7/home/t-goto/HiCUP-0.8.3/hicup_mapper line 240.
Nature_neuro/results/SRR12066917_1_2.pair.bam contains no data
All the files in the HiCUP pipeline have been removed for containing no data.

**Comment by StevenWingett** [comment]
Hi,

There seem to be 2 issues.

1). It doesn't appear as if R is set up correctly and needs access to shared libraries: libblas.so.3.  If you run R  (/home/t-goto/local/lib64/R/bin/exec/R) from the command line, does it work correctly?

Actually, HiCUP shouldn't need R to work - R is used to generate figures, but these are not essential.

2). The HiCUP pipeline is not completing properly.  Are you able to process the test dataset?

The error you see is usually a result of your system not having enough RAM allocated to the job.  If you allocate 30GB RAM, can you process the test dataset?

I hope that helps,
Steven

**Comment by TakatoG** [comment]
Hi, I understand.
Thank you.
Also I want to ask about another problem as follows,
In my local, seems the could not create html of test data set.
--------------------------------------------------------------
Could not generate HiCUP HTML summary report with run command 'R -e "rmarkdown::render('/Users/takato/HiCUP-0.8.3/r_scripts/hicup_reporter.rmd', params=list(summary_file='/Users/takato/test_dataset1_2.hicup.bam.HiCUP_summary_report_GBirhDxiMo_20-08-59_09-02-2023.txt', ditag_lengths_file='/Users/takato/test_dataset1_2.ditag_size_distribution_report.txt'), intermediates_dir='/Users/takato/', output_file='/Users/takato/test_dataset1_2.hicup.bam.HiCUP_summary_report_GBirhDxiMo_20-08-59_09-02-2023.html')" > /dev/null 2>&1'
Created HTML summary reports
HiCUP processing complete.

What is this error??

**Comment by TakatoG** [comment]
Hi, I understand.
Thank you.
Also I want to ask about another problem as follows,
In my local, seems the could not create html of test data set.

Could not generate HiCUP HTML summary report with run command 'R -e "rmarkdown::render('/Users/takato/HiCUP-0.8.3/r_scripts/hicup_reporter.rmd', params=list(summary_file='/Users/takato/test_dataset1_2.hicup.bam.HiCUP_summary_report_GBirhDxiMo_20-08-59_09-02-2023.txt', ditag_lengths_file='/Users/takato/test_dataset1_2.ditag_size_distribution_report.txt'), intermediates_dir='/Users/takato/', output_file='/Users/takato/test_dataset1_2.hicup.bam.HiCUP_summary_report_GBirhDxiMo_20-08-59_09-02-2023.html')" > /dev/null 2>&1'
Created HTML summary reports
HiCUP processing complete.

What is this error??

**Comment by TakatoG** [comment]
Hi, I understand.
Thank you.
Also I want to ask about another problem as follows,
In my local, seems that could not create html of test data set.

Could not generate HiCUP HTML summary report with run command 'R -e "rmarkdown::render('/Users/takato/HiCUP-0.8.3/r_scripts/hicup_reporter.rmd', params=list(summary_file='/Users/takato/test_dataset1_2.hicup.bam.HiCUP_summary_report_GBirhDxiMo_20-08-59_09-02-2023.txt', ditag_lengths_file='/Users/takato/test_dataset1_2.ditag_size_distribution_report.txt'), intermediates_dir='/Users/takato/', output_file='/Users/takato/test_dataset1_2.hicup.bam.HiCUP_summary_report_GBirhDxiMo_20-08-59_09-02-2023.html')" > /dev/null 2>&1'
Created HTML summary reports
HiCUP processing complete.

What is this error??

**Comment by TakatoG** [comment]
Hi,
I understand! Thank you!
