### ISSUE TITLE
create_baitmap_rmap.pl

### ISSUE THREAD

**Issue by TakatoG** [StevenWingett/HiCUP#77]
Hi, 
I am so sorry but I want to ask about CHiCAGO after HiCUP analyzing.
I want to make rmap and baitmap as follows command by chicagotools;
create_baitmap_rmap.pl
and then,
Specify i) digest file and ii) oligos file

Where can I get  ii) oligos file ??

**Comment by StevenWingett** [comment]
Hi,

Are you using our capture design system?  If so, the oligos should have been made available in the original CHiCAGO papers? 

If you are using you own design system, you can use the file mentioned above as a template for your own oligos files.

Does that help?

All the best,
Steven

**Comment by TakatoG** [comment]
Hi,
Resolved! Thank you very much.
I had another problem with using bam2chicago.sh.

 I would like to create a chinput with .bam, but how can I deal with the following error?
First, I merge the bam obtained by HiCUP, then sorted,indexed and typed the following command.

sh bam2chicago.sh /Users/takato/reactivated_bam/reactivated_sorted.bam /Users/takato/mm9_Hind/Digest_mm9_HindIII_baits_ID.baitmap /Users/takato/mm9_Hind/Digest_mm9_HindIII.rmap chinput

Checking rmap and baitmap files...
Rmap and baitmap files checked successfully
Processing sample chinput...
Using bam file /Users/takato/reactivated_bam/reactivated_sorted.bam
Using baitmap file /Users/takato/mm9_Hind/Digest_mm9_HindIII_baits_ID.baitmap
Using digest map (rmap) file /Users/takato/mm9_Hind/Digest_mm9_HindIII.rmap
Baitmap file contains >4 columns. Checking if /Users/takato/mm9_Hind/Digest_mm9_HindIII_baits_ID.baitmap_4col.txt exists...
It doesn't. So trimming the extra columns and saving the result in /Users/takato/mm9_Hind/Digest_mm9_HindIII_baits_ID.baitmap_4col.txt...
Intersecting with bait fragments (using min overhang of 0.6)...
*****WARNING: Query SRR12066916.4807393 is marked as paired, but it's mate does not occur next to it in your BAM file.  Skipping. 
*****WARNING: Query SRR12066916.11342995 is marked as paired, but it's mate does not occur next to it in your BAM file.  Skipping. 
*****WARNING: Query SRR12066916.11681002 is marked as paired, but it's mate does not occur next to it in your BAM file.  Skipping. 
*****WARNING: Query SRR12066917.1783759 is marked as paired, but it's mate does not occur next to it in your BAM file.  Skipping. 
*****WARNING: Query SRR12066917.3725441 is marked as paired, but it's mate does not occur next to it in your BAM file.  Skipping. 
*****WARNING: Query SRR12066917.8000241 is marked as paired, but it's mate does not occur next to it in your BAM file.  Skipping. 
*****WARNING: Query SRR12066916.9492277 is marked as paired, but it's mate does not occur next to it in your BAM file.  Skipping.

**Comment by TakatoG** [comment]
Hi! 
Thank you for reply!
I understand.

I also have another problem using bam2chicago_V02.sh.

(base) takato@TakatonoMacBook-Air chicagoTools % sh bam2chicago_V02.sh -b /Users/takato/reactivated_bam/SRR12066914_1_2.hicup.bam -t /Users/takato/mm9_Hind/Digest_mm9_HindIII_baits_ID.baitmap -r /Users/takato/mm9_Hind/Digest_mm9_HindIII.rmap -o chinput

Checking rmap and baitmap files...
Rmap and baitmap files checked successfully
Processing sample chinput...
Using bam file /Users/takato/reactivated_bam/SRR12066914_1_2.hicup.bam
Using baitmap file /Users/takato/mm9_Hind/Digest_mm9_HindIII_baits_ID.baitmap
Using digest map (rmap) file /Users/takato/mm9_Hind/Digest_mm9_HindIII.rmap
Baitmap file contains >4 columns. Checking if /Users/takato/mm9_Hind/Digest_mm9_HindIII_baits_ID.baitmap_4col.txt exists...
Found /Users/takato/mm9_Hind/Digest_mm9_HindIII_baits_ID.baitmap_4col.txt
Intersecting with bait fragments (using min overhang of 0.6)...
Flipping all reads that overlap with the bait on to the right-hand side...
Intersecting with bait fragments again to produce a list of bait-to-bait interactions that can be used separately; note they will also be retained in the main output...
Intersecting with restriction fragments (using min overhang of 0.6)...
Removing reads that failed the min overhang filter...
Adding frag length and signed distance from bait; removing self-ligation fragments (if any; not expected with HiCUP input)...
Can't open chinput/SRR12066914_1_2.hicup_mappedToBaitsBoRAndRFrag_fmore06.bedpe: No such file or directory.
rm: chinput/SRR12066914_1_2.hicup_mappedToBaitsBoRAndRFrag_fmore06.bedpe: No such file or directory
Pooling read pairs...
Done! The file to be used for Chicago R package input is chinput/chinput.chinput


How can I solve this??

**Comment by StevenWingett** [comment]
Hi,

I don't know, but this appears to be an issue with CHiCAGO.  Did you make all the appropriate rmap, baitmap files?  You normally need to do this before running CHiCAGO.

Does this help: https://lms.mrc.ac.uk/best-practice-guide-for-chicago-protocol-used-in-analysis-of-capture-hi-c-data/

If not, could you please contact the CHiCAGO developers  - I've not been working on this project for many years now.

Thanks,
Steven
