### ISSUE TITLE
Change version

### ISSUE THREAD

**Issue by lldelisle** [StevenWingett/HiCUP#86]
I think you forgot to change the version number in the code...
https://github.com/StevenWingett/HiCUP/blob/f4f6b9da00ae1d406e714859e5a40610fe9b82ee/hicup_module.pm#L11

**Comment by StevenWingett** [comment]
Oh dear.  I've made a few documentation changes, changed the version number and pushed release v0.9.2.

Thanks.

**Comment by lldelisle** [comment]
Version 0.9.2 on conda: https://anaconda.org/bioconda/hicup
You can even add a badge if you want:
![badge](https://anaconda.org/bioconda/hicup/badges/version.svg)

**Comment by StevenWingett** [comment]
Thanks, I have updated the manual.
