### ISSUE TITLE
How to specify the bowtie2 option

### ISSUE THREAD

**Issue by TakatoG** [StevenWingett/HiCUP#90]
Hi
Could you please tell me how to specify the bowtie2 option?

(base) [t-goto@at137 ~]$ singularity exec /usr/local/biotools/h/hicup:0.8.3--hdfd78af_1 hicup --bowtie2 -very-sensitive --config HiCUP-0.8.3/config_files/hicup_example3.conf
Starting HiCUP pipeline (v0.8.3)
PLEASE NOTE: FROM VERSION 8, HICUP REQUIRES THE R PACKAGES TIDYVERSE AND PLOTLY INSTALLED
SEE DOCUMENTATION FOR MORE DETAILS
Aligner not found at '-very-sensitive'
Looking for aligner at '-very-sensitive/bowtie2'
Aligner not found at '-very-sensitive/bowtie2'
Trying to find 'bowtie2' automatically

Best regards

**Comment by StevenWingett** [comment]
Hi,

The flag --bowtie2 is for specifying the path to Bowtie2 and is not for passing options to Bowtie2.

There is not a HiCUP flag to modify how Bowtie2 maps reads.  However, the Bowtie option --very-sensitive is actually the parameter already used by the aligner: see line 332 at https://github.com/StevenWingett/HiCUP/blob/master/hicup_mapper

I hope that helps.

Regards,
Steven
