### ISSUE TITLE
Error encountered while working on HiCUP

### ISSUE THREAD

**Issue by Nandhininj** [StevenWingett/HiCUP#91]
Hello,
I am a Researcher from Bangalore, India, trying to work on HiCUP. I encountered an error while running the pipeline and I request your help for the same. 
error -
Can't read './test_dataset1.map.sam' : No such file or directory at /mnt/f/HiC_pipeline/HICUP-0.9.2/hicup_mapper line 552.
I have attached a screenshot of my terminal. I have been working on WSL (Windows sub-system for Linux). 

Thanks in advance!!
![unnamed](https://github.com/StevenWingett/HiCUP/assets/133749941/d760e215-754b-4b01-951f-62ca37658022)

**Comment by StevenWingett** [comment]
Hi,

Take a look at:

https://github.com/StevenWingett/HiCUP/issues/57#issuecomment-900505087

It may be that you need to allocate more RAM to the job on your system.  Does that help?

Best,

Steven
