### ISSUE TITLE
New issue encountered

### ISSUE THREAD

**Issue by Nandhininj** [StevenWingett/HiCUP#95]
![IMG_2421](https://github.com/StevenWingett/HiCUP/assets/133749941/6670362b-d9e9-4dd7-ac93-25464e08deaf)

Dear Mr Wingett,
I am a Researcher from Bangalore, India, trying to work on HiCUP. I encountered an error while running the pipeline and I request your help for the same. I have attached a screenshot of my terminal.

Thanks & Regards, 
Nandhini N J

**Comment by StevenWingett** [comment]
Hi Nandhini N J,

This occurs when there is a mis-match between the FASTA file(s) used to create the Bowtie2 index and the FASTA file(s) used to create the HiCUP digest file.

So, I recommend making the HiCUP Digest file and the Bowtie2 index files again, from the same FASTA file(s).

Best,
Steven
