### ISSUE TITLE
fileNamer error for genome indices 

### ISSUE THREAD

**Issue by kaileeyoshimura** [StevenWingett/HiCUP#96]
Hi Steven, 

I downloaded both HiCUP and the test datasets following the "How to run HiCUP" youtube video, created Bowtie2 indices, and made a digest file. I edited the test config file, following the video, with the correct directories to the indices, digested file, Bowtie2, and both test datasets. 

At first I was receiving this error when I ran my config file: "**When selecting 'all' for fileNamer, input options need to be 10000 or 11111.**"

(Here is a list of the files in my reference genome indices directory: Homo_sapien.GRCh38.1.bt2  Homo_sapien.GRCh38.3.bt2  Homo_sapien.GRCh38.rev.1.bt2 Homo_sapien.GRCh38.2.bt2  Homo_sapien.GRCh38.4.bt2  Homo_sapien.GRCh38.rev.2.bt2)

I added 10000 (and I also tried 11111) below the indices directory, which resolved the fileNamer error, but a new error popped up. "**There needs to be an even number of files in the configuration file, see hicup --help for more details**."

I also tried removing 10000/11111 from the config file and adding a --fileNamer argument when running my config file: 
`HiCUP-0.9.2/hicup --config hicup_example.conf --fileNamer 10000` 

Which gives me this error: "**Command line options need to be in the correct format (hicup -help for more details).**"

I'm not sure how to get past these errors, below is a truncated version of my config file. 

```
#Path to the alignment program (Bowtie or Bowtie2)
#Remember to include the executable Bowtie/Bowtie2 filename.
#Note: ensure you specify the correct aligner i.e. Bowtie when
#using Bowtie indices, or Bowtie2 when using Bowtie2 indices.
#In the example below Bowtie2 is specified.
Bowtie2: /u/local/apps/bowtie2/2.4.2/bowtie2

#Path to the reference genome indices
#Remember to include the basename of the genome indices
Index: Bowtie_GRCh38/Homo_sapien.GRCh38
10000

#Path to the genome digest file produced by hicup_digester
Digest: Digest_Human_GRCh38_HindIII_None_10-22-16_30-08-2023.txt


#FASTQ format (valid formats: 'Sanger', 'Solexa_Illumina_1.0', 'Illumina_1.3' or 'Illumina_1.5')
#If not specified, HiCUP will try to determine the format automatically by analysing
#one of the FASTQ files. All input FASTQ will assumed to be in this format
Format: Sanger

#Maximum di-tag length (optional parameter)
Longest: 700


#Minimum di-tag length (optional parameter)
Shortest: 50


#FASTQ files to be analysed, placing paired files on adjacent lines
test_dataset/test_dataset1.fastq
test_dataset/test_dataset2.fastq
```

**Comment by StevenWingett** [comment]
Hi,

I've never seen that error message before.  

Would you send me:

1: The full config file you used (as an attachment).
2: The command you entered on the command line
3: The full output from HiCUP written to the screen.

Thanks,
Steven

**Comment by StevenWingett** [comment]
(Also, you should not enter 10000 in the config file or as a command-line option.)

Thanks.

**Comment by kaileeyoshimura** [comment]
I've attached the full config file. I'm not able to upload the config version, so I made it into a .txt file.
[hicup_example.txt](https://github.com/StevenWingett/HiCUP/files/12752210/hicup_example.txt)

The command I entered: `HiCUP-0.9.2/hicup --config hicup_example.conf`

Full output from HiCUP: 
Starting HiCUP pipeline (v0.9.2)
PLEASE NOTE: FROM VERSION 8, HICUP REQUIRES THE R PACKAGES TIDYVERSE AND PLOTLY INSTALLED
SEE DOCUMENTATION FOR MORE DETAILS
Could not find SAMtools (http://samtools.sourceforge.net), please install if you wish to compress SAM files to BAM format
Detecting R automatically
Could not find R (www.r-project.org), please install if graphs are required
When selecting 'all' for fileNamer, input options need to be 10000 or 11111.

**Comment by StevenWingett** [comment]
Hi again,

I have never seen HiCUP report this error message before.  The one thing I have noticed is that it is unusual to not have Samtools installed.  Could you try installing Samtools and gzip (and preferably R and pandoc as well).  Also, I recommend gzipping files i.e. add Zip:1 to the config file.

Does this problem still occur?

Thanks,
Steven

**Comment by kaileeyoshimura** [comment]
Hi Steven, 

It worked! Thank you for the suggestions. I'm running HiCUP on a cluster, so I needed to reload R before I submitted the HiCUP command. Thanks again for your help!
