### ISSUE TITLE
Trimming step before HiCUP?

### ISSUE THREAD

**Issue by iagooteroc** [StevenWingett/HiCUP#99]
Hi. 
Would it be good to start by trimming the adapters before running HiCUP, or would it be unnecessary given the truncating step?
Thank you

**Comment by StevenWingett** [comment]
Hi,

Adapter/quality trimming prior to using HiCUP is a good idea.  (HiCUP does not trim for quality, but rather for the presence of a HiC ligation junction),

I would recommend trimming with TrimGalore! in paired-end mode ( see https://www.bioinformatics.babraham.ac.uk/projects/trim_galore/ )

Steven
